# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# COMPILER_WORKS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set COMPILER_WORKS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The COMPILER_WORKS_COMPILED variable holds the build result for this TRY_RUN().

set( COMPILER_WORKS_EXITCODE 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)

#set( COMPILER_WORKS_EXITCODE 
#     "0"
#     CACHE STRING "Result from TRY_RUN" FORCE)
#
#set( COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT 
#     ""
#     CACHE STRING "Output from TRY_RUN" FORCE)

