# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes directories, add to BBFILES
BBFILES += "\
	${LAYERDIR}/*/*.bb \
	${LAYERDIR}/*/*.bbappend \
	${LAYERDIR}/*/*/*.bb \
	${LAYERDIR}/*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "ml-layer"
BBFILE_PATTERN_ml-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_ml-layer = "7"

LAYERDEPENDS_ml-layer = "core meta-python"

LAYERSERIES_COMPAT_ml-layer = "scarthgap"
